#!/usr/bin/env python3
"""Send completion email for Ownership Attribution addition"""
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime

# SMTP Configuration
SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = 587
SMTP_USER = "janfrancisisrael@gmail.com"
SMTP_PASSWORD = "goyz tpmm dtxm mjib"

# Email details
TO_EMAIL = "janfrancisisrael@gmail.com"
FROM_EMAIL = "janfrancisisrael@gmail.com"

def send_email():
    """Send completion email"""
    try:
        # Create message
        msg = MIMEMultipart()
        msg['From'] = FROM_EMAIL
        msg['To'] = TO_EMAIL
        msg['Subject'] = "✅ Ownership Attribution Added - Cortex AI Legal Pages"
        
        # Email body
        body = f"""
Hello Swordfish,

The ownership and design attribution section has been successfully added to both legal pages.

📋 **Completed Updates:**

1. ✅ **Ownership Statement**
   - Added clear ownership declaration: "Cortex AI is owned and operated by Jan Francis Israel"
   - All rights reserved statement included

2. ✅ **Design Attribution**
   - Added attribution to Themesberg Neumorphism UI Bootstrap framework
   - Clearly states that the neumorphism design elements and styling are based on Themesberg Neumorphism UI Kit
   - Includes link to Themesberg product page: https://themesberg.com/products/neumorphism-ui

3. ✅ **Intellectual Property Clarification**
   - States that all content and functionality (except design framework) are property of Jan Francis Israel
   - Protected by copyright and intellectual property laws

📄 **Pages Updated:**
- Privacy Policy (/privacy-policy)
- Terms of Service (/terms-of-service)

Both pages now include a dedicated "Ownership and Design Attribution" section before the Contact Us section, styled consistently with the neumorphism design.

🚀 **Deployment:**
- Changes committed and pushed to v2-appearance branch
- Ready for CI/CD deployment to production

---
Generated by Agimat (Super Debugger AI)
Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
        """
        
        msg.attach(MIMEText(body, 'plain'))
        
        # Send email
        server = smtplib.SMTP(SMTP_SERVER, SMTP_PORT)
        server.starttls()
        server.login(SMTP_USER, SMTP_PASSWORD)
        text = msg.as_string()
        server.sendmail(FROM_EMAIL, TO_EMAIL, text)
        server.quit()
        
        print("✅ Email sent successfully!")
        return True
        
    except Exception as e:
        print(f"❌ Error sending email: {e}")
        import traceback
        traceback.print_exc()
        return False

if __name__ == "__main__":
    send_email()

