#!/usr/bin/env python3
"""Send completion email for Legal Pages Redesign"""
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime

# SMTP Configuration
SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = 587
SMTP_USER = "janfrancisisrael@gmail.com"
SMTP_PASSWORD = "goyz tpmm dtxm mjib"

# Email details
TO_EMAIL = "janfrancisisrael@gmail.com"
FROM_EMAIL = "janfrancisisrael@gmail.com"

def send_email():
    """Send completion email"""
    try:
        # Create message
        msg = MIMEMultipart()
        msg['From'] = FROM_EMAIL
        msg['To'] = TO_EMAIL
        msg['Subject'] = "✅ Legal Pages Redesigned - Dashboard Design Applied"
        
        # Email body
        body = f"""
Hello Swordfish,

The Privacy Policy and Terms of Service pages have been successfully redesigned to match the dashboard design.

🎨 **Design Updates:**

1. ✅ **Dashboard Header Integration**
   - Both pages now use the same dashboard header component
   - Includes hamburger menu, logo, navigation, user info, and logout button
   - Consistent header styling across all pages

2. ✅ **Dashboard Styling Applied**
   - Uses dashboard.css for consistent styling
   - Content wrapped in dashboard container structure
   - Legal content displayed in dashboard card components
   - Same color scheme, typography, and spacing as dashboard

3. ✅ **User Experience Improvements**
   - Added "Back to Dashboard" link at top of pages
   - Pages now require login (matching dashboard access)
   - User context passed to templates for header display
   - Responsive design maintained

4. ✅ **Content Structure**
   - All legal content retained
   - Ownership and design attribution sections preserved
   - Contact information displayed in styled card
   - Material Icons integrated throughout

📄 **Pages Updated:**
- Privacy Policy (/privacy-policy)
- Terms of Service (/terms-of-service)

Both pages now have a consistent look and feel with the dashboard, providing a seamless user experience.

🚀 **Deployment:**
- Changes committed and pushed to v2-appearance branch
- Ready for CI/CD deployment to production

**Next Steps:**
- CI/CD pipeline will automatically deploy to production
- Legal pages will be accessible at:
  - https://cortex.janisrael.com/privacy-policy
  - https://cortex.janisrael.com/terms-of-service

---
Generated by Agimat (Super Debugger AI)
Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
        """
        
        msg.attach(MIMEText(body, 'plain'))
        
        # Send email
        server = smtplib.SMTP(SMTP_SERVER, SMTP_PORT)
        server.starttls()
        server.login(SMTP_USER, SMTP_PASSWORD)
        text = msg.as_string()
        server.sendmail(FROM_EMAIL, TO_EMAIL, text)
        server.quit()
        
        print("✅ Email sent successfully!")
        return True
        
    except Exception as e:
        print(f"❌ Error sending email: {e}")
        import traceback
        traceback.print_exc()
        return False

if __name__ == "__main__":
    send_email()

